### ISSUE TITLE
Multiaddr formatter doesn't work

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-logger#35]
The formatter added in https://github.com/libp2p/js-libp2p-logger/pull/34 doesn't work:

Code:

```js
log('%ma is externally dialable', addr)
```

Log output:

```
libp2p:autonat a is externally dialable +0ms
```

cc @maschad @MarcoPolo

**Comment by maschad** [comment]
Good catch, since [debug-js](https://github.com/debug-js/debug#formatters) uses [printf-style](https://wikipedia.org/wiki/Printf_format_string) formatting, `%ma` wouldn't work. I pushed a [fix](https://github.com/libp2p/js-libp2p-logger/pull/36).
